import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";
import { ThemeProvider } from "./providers/ThemeProvider";
import AuthProvider from "./providers/AuthProvider";
import SessionWrapper from "./providers/SessionWrapper";
import { NextIntlClientProvider } from "next-intl";
import DataProvider from "./providers/DataProvider";
import NavigationBar from "../components/bottomBar";
import HeightProvider from "./providers/HeightProvider";
import ContentProvider from "./providers/ContentProvider";

interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, locale }: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className="!overscroll-none">
        <StoreProvider>
          <NextIntlClientProvider>
            <SessionWrapper>
              <ThemeProvider>
                <AuthProvider>
                  <DataProvider>{children}</DataProvider>
                </AuthProvider>
              </ThemeProvider>
            </SessionWrapper>
          </NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
