import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";
import { ThemeProvider } from "./providers/ThemeProvider";
import AuthProvider from "./providers/AuthProvider";
import SessionWrapper from "./providers/SessionWrapper";
import DataProvider from "./providers/DataProvider";
import HeightProvider from "./providers/HeightProvider";
import ContentProvider from "./providers/ContentProvider";
import NextTopLoader from "nextjs-toploader";

interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, locale }: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className="!overscroll-none">
        <StoreProvider>
          <SessionWrapper>
            <ThemeProvider>
              <AuthProvider>
                <DataProvider>
                  <HeightProvider>
                    <ContentProvider>
                      {children}
                    </ContentProvider>
                  </HeightProvider>
                </DataProvider>
              </AuthProvider>
            </ThemeProvider>
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
