import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import NavigationBar from "../../components/bottomBar";
import ContentProvider from "../providers/ContentProvider";
import HeightProvider from "../providers/HeightProvider";
import { ThemeProvider } from "../providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} className="dark">
      <body>
        <HeightProvider>
          <ContentProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ContentProvider>
        </HeightProvider>
        <Toaster />
      </body>
    </html>
  );
}
